# MAIN CONFIGURATION

app.name = Spark Studio
app.version = 16.7.5
app.versionCode = autumn
app.hash = 2024080100
app.uuid =
app.implicitExit = 0

# APP
app.namespace = ide
app.mainForm = MainForm
app.splashForm = SplashForm
app.showMainForm = 1

app.icon = .data/img/SparkIco.png

app.fx.splash.autoHide = 1