# MAIN CONFIGURATION

app.name = Spark Studio
app.version = 17.0.1
app.versionCode = autumn
app.hash = 2024080100
app.uuid =
app.implicitExit = 0

# APP
app.namespace = ide
app.mainForm = MainForm
app.splashForm = SplashForm
app.showMainForm = 1

app.icon = .data/img/SparkIco.ico

app.fx.splash.autoHide = 1